### ISSUE TITLE
square images are not shown up when I use my browser at half the viewport 

### ISSUE THREAD

**Issue by you00019** [you00019/Picture-This#1] opened 2022-06-13 16:04 UTC
Dear professor @@abhaysharma

My square images are not shown up when I use my browser at half the viewport, could you please help me look at my code?

Thanks a lot~

Jia

**Comment by abhaysharma** [comment] 2022-06-13 18:53
@you00019 the issue is with the order of the source tags media. 
Since you are using min-width for all source tags you will need the largest size at the top followed by the smaller size and so on. min-width: 1600px should be at the top, then min-width: 1280px then min-width: 960px and so on.

**Comment by you00019** [comment] 2022-06-13 18:56
hi professor @abhaysharma, thanks for your reply! 
I just updated my code 1 min ago, but it still shows the same issue. :(

**Comment by abhaysharma** [comment] 2022-06-13 19:08
@you00019 I still see the same HTML. Please make sure your sources with different media sizes are in proper order, largest size first.

**Comment by you00019** [comment] 2022-06-13 19:47
@abhaysharma thanks a lot professor, I think i have solved this problem. 
have a nice day!

**Comment by abhaysharma** [comment] 2022-06-15 16:28
@you00019 you can close this issue now.

**Comment by you00019** [comment] 2022-06-15 16:29
thanks, professor! :)

**Closed as completed** 2022-06-15 16:29 UTC
